import { HighlightStyle } from "@codemirror/language";
import type { Theme } from "./index";
import { tags as t } from "@lezer/highlight";

export const gnomeLightSyntax: HighlightStyle = HighlightStyle.define([
  { tag: t.comment, color: "#8c8c8c", fontStyle: "italic" },
  { tag: t.lineComment, color: "#8c8c8c", fontStyle: "italic" },
  { tag: t.blockComment, color: "#8c8c8c", fontStyle: "italic" },
  { tag: t.docComment, color: "#8c8c8c", fontStyle: "italic" },
  { tag: t.keyword, color: "#9c27d0" },
  { tag: t.controlKeyword, color: "#9c27d0" },
  { tag: t.definitionKeyword, color: "#9c27d0" },
  { tag: t.moduleKeyword, color: "#9c27d0" },
  { tag: t.operatorKeyword, color: "#9c27d0" },
  { tag: t.self, color: "#a6283a" },
  { tag: t.null, color: "#b07533" },
  { tag: t.atom, color: "#b07533" },
  { tag: t.bool, color: "#b07533" },
  { tag: t.number, color: "#b07533" },
  { tag: t.integer, color: "#b07533" },
  { tag: t.float, color: "#b07533" },
  { tag: t.string, color: "#4a8540" },
  { tag: t.docString, color: "#4a8540" },
  { tag: t.character, color: "#4a8540" },
  { tag: t.escape, color: "#4a8540" },
  { tag: t.regexp, color: "#4a8540" },
  { tag: t.variableName, color: "#333333" },
  { tag: t.propertyName, color: "#a07d1a" },
  { tag: t.function(t.variableName), color: "#1e6bb8" },
  { tag: t.function(t.propertyName), color: "#1e6bb8" },
  { tag: t.labelName, color: "#a07d1a" },
  { tag: t.namespace, color: "#1e6bb8" },
  { tag: t.typeName, color: "#8a6d1a" },
  { tag: t.className, color: "#8a6d1a" },
  { tag: t.macroName, color: "#1e6bb8" },
  { tag: t.attributeName, color: "#b07533" },
  { tag: t.tagName, color: "#a6283a" },
  { tag: t.operator, color: "#505050" },
  { tag: t.derefOperator, color: "#505050" },
  { tag: t.arithmeticOperator, color: "#505050" },
  { tag: t.logicOperator, color: "#505050" },
  { tag: t.compareOperator, color: "#505050" },
  { tag: t.updateOperator, color: "#505050" },
  { tag: t.definitionOperator, color: "#505050" },
  { tag: t.punctuation, color: "#666666" },
  { tag: t.separator, color: "#666666" },
  { tag: t.bracket, color: "#666666" },
  { tag: t.invalid, color: "#ffffff", backgroundColor: "#c01c28" },
  { tag: t.meta, color: "#8c8c8c" },
]);

export const gnomeLightTheme: Theme = {
  name: "Gnome Light",
  variant: "light",

  bg: "#f5f5f5",
  fg: "#333333",
  muted: "#686868",
  hover: "#ededed",
  active: "#dcdcdc",
  activeFg: "#000000",
  border: "#e0e0e0",
  accent: "#3584e4",

  editorBg: "#ffffff",
  editorFg: "#333333",
  gutterBg: "#ffffff",
  gutterFg: "#686868",
  activeLine: "#ededed",
  activeLineGutter: "#e8e8e8",
  selection: "#b3d4fc",
  cursor: "#333333",
  whitespace: "#e0e0e0",
  matchingBracket: "#dcdcdc",

  inputBg: "#e0e0e0",
  inputFg: "#333333",
  inputBorder: "#c8c8c8",
  inputHover: "#d4d4d4",
  inputFocus: "#3584e4",

  syntax: gnomeLightSyntax,
};
