import { HighlightStyle } from "@codemirror/language";
import type { Theme } from "./index";
import { tags as t } from "@lezer/highlight";

export const gnomeDarkSyntax: HighlightStyle = HighlightStyle.define([
  { tag: t.comment, color: "#878787", fontStyle: "italic" },
  { tag: t.lineComment, color: "#878787", fontStyle: "italic" },
  { tag: t.blockComment, color: "#878787", fontStyle: "italic" },
  { tag: t.docComment, color: "#878787", fontStyle: "italic" },
  { tag: t.keyword, color: "#c678dd" },
  { tag: t.controlKeyword, color: "#c678dd" },
  { tag: t.definitionKeyword, color: "#c678dd" },
  { tag: t.moduleKeyword, color: "#c678dd" },
  { tag: t.operatorKeyword, color: "#c678dd" },
  { tag: t.self, color: "#e5c07b" },
  { tag: t.null, color: "#d19a66" },
  { tag: t.atom, color: "#d19a66" },
  { tag: t.bool, color: "#d19a66" },
  { tag: t.number, color: "#d19a66" },
  { tag: t.integer, color: "#d19a66" },
  { tag: t.float, color: "#d19a66" },
  { tag: t.string, color: "#98c379" },
  { tag: t.docString, color: "#98c379" },
  { tag: t.character, color: "#98c379" },
  { tag: t.escape, color: "#98c379" },
  { tag: t.regexp, color: "#98c379" },
  { tag: t.variableName, color: "#ECE9E2" },
  { tag: t.propertyName, color: "#e1c13d" },
  { tag: t.function(t.variableName), color: "#61afef" },
  { tag: t.function(t.propertyName), color: "#61afef" },
  { tag: t.labelName, color: "#e1c13d" },
  { tag: t.namespace, color: "#61afef" },
  { tag: t.typeName, color: "#e5c07b" },
  { tag: t.className, color: "#e5c07b" },
  { tag: t.macroName, color: "#61afef" },
  { tag: t.attributeName, color: "#d19a66" },
  { tag: t.tagName, color: "#e06c75" },
  { tag: t.operator, color: "#D1D1D1" },
  { tag: t.derefOperator, color: "#D1D1D1" },
  { tag: t.arithmeticOperator, color: "#D1D1D1" },
  { tag: t.logicOperator, color: "#D1D1D1" },
  { tag: t.compareOperator, color: "#D1D1D1" },
  { tag: t.updateOperator, color: "#D1D1D1" },
  { tag: t.definitionOperator, color: "#D1D1D1" },
  { tag: t.punctuation, color: "#abb2bf" },
  { tag: t.separator, color: "#abb2bf" },
  { tag: t.bracket, color: "#abb2bf" },
  { tag: t.invalid, color: "#ffffff", backgroundColor: "#9c101a" },
  { tag: t.meta, color: "#878787" },
]);

export const gnomeDarkTheme: Theme = {
  name: "Gnome Dark",
  variant: "dark",

  bg: "#1f1f1f",
  fg: "#eeeeec",
  muted: "#a0a0a0",
  hover: "#3b3b3b",
  active: "#3584e4",
  activeFg: "#ffffff",
  border: "#3d3d3d",
  accent: "#3584e4",
  info: "#205faa",
  error: "#9c101a",
  warn: "#c2a131",
  hint: "#c061cb",

  editorBg: "#242424",
  editorFg: "#D1D1D1",
  gutterBg: "#282828",
  gutterFg: "#a0a0a0",
  activeLine: "#303030",
  activeLineGutter: "#303030",
  selection: "#2b6fc2",
  cursor: "#D1D1D1",
  whitespace: "#3d3d3d",
  matchingBracket: "#3d3d3d",

  inputBg: "#464646",
  inputFg: "#eeeeec",
  inputBorder: "#464646",
  inputHover: "#555555",
  inputFocus: "#448ce3",

  syntax: gnomeDarkSyntax,
};
