import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import type { Extension } from "@codemirror/state";
import { tags as t } from "@lezer/highlight";
import type { Theme } from "./index";

export const darkSyntaxStyle: HighlightStyle = HighlightStyle.define([
  { tag: t.comment, color: "#6b7280", fontStyle: "italic" },
  { tag: t.lineComment, color: "#6b7280", fontStyle: "italic" },
  { tag: t.blockComment, color: "#6b7280", fontStyle: "italic" },
  { tag: t.docComment, color: "#8b95a7", fontStyle: "italic" },
  { tag: t.keyword, color: "#c678dd" },
  { tag: t.controlKeyword, color: "#c678dd" },
  { tag: t.definitionKeyword, color: "#c678dd" },
  { tag: t.moduleKeyword, color: "#c678dd" },
  { tag: t.operatorKeyword, color: "#c678dd" },
  { tag: t.self, color: "#e06c75" },
  { tag: t.null, color: "#56b6c2" },
  { tag: t.atom, color: "#56b6c2" },
  { tag: t.bool, color: "#56b6c2" },
  { tag: t.number, color: "#56b6c2" },
  { tag: t.integer, color: "#56b6c2" },
  { tag: t.float, color: "#56b6c2" },
  { tag: t.string, color: "#98c379" },
  { tag: t.docString, color: "#98c379" },
  { tag: t.character, color: "#98c379" },
  { tag: t.escape, color: "#56b6c2" },
  { tag: t.regexp, color: "#e5c07b" },
  { tag: t.variableName, color: "#e06c75" },
  { tag: t.propertyName, color: "#e5c07b" },
  { tag: t.function(t.variableName), color: "#61afef" },
  { tag: t.function(t.propertyName), color: "#61afef" },
  { tag: t.labelName, color: "#e5c07b" },
  { tag: t.namespace, color: "#61afef" },
  { tag: t.typeName, color: "#e5c07b" },
  { tag: t.className, color: "#e5c07b" },
  { tag: t.macroName, color: "#61afef" },
  { tag: t.operator, color: "#56b6c2" },
  { tag: t.derefOperator, color: "#56b6c2" },
  { tag: t.arithmeticOperator, color: "#56b6c2" },
  { tag: t.logicOperator, color: "#c678dd" },
  { tag: t.compareOperator, color: "#c678dd" },
  { tag: t.updateOperator, color: "#56b6c2" },
  { tag: t.definitionOperator, color: "#c678dd" },
  { tag: t.punctuation, color: "#abb2bf" },
  { tag: t.separator, color: "#abb2bf" },
  { tag: t.bracket, color: "#abb2bf" },
  { tag: t.invalid, color: "#ffffff", backgroundColor: "#e05252" },
  { tag: t.meta, color: "#6b7280" },
]);

export const lightSyntaxStyle: HighlightStyle = HighlightStyle.define([
  { tag: t.comment, color: "#6a737d", fontStyle: "italic" },
  { tag: t.lineComment, color: "#6a737d", fontStyle: "italic" },
  { tag: t.blockComment, color: "#6a737d", fontStyle: "italic" },
  { tag: t.docComment, color: "#6a737d", fontStyle: "italic" },
  { tag: t.keyword, color: "#d73a49" },
  { tag: t.controlKeyword, color: "#d73a49" },
  { tag: t.definitionKeyword, color: "#d73a49" },
  { tag: t.moduleKeyword, color: "#d73a49" },
  { tag: t.operatorKeyword, color: "#d73a49" },
  { tag: t.self, color: "#005cc5" },
  { tag: t.null, color: "#005cc5" },
  { tag: t.atom, color: "#005cc5" },
  { tag: t.bool, color: "#005cc5" },
  { tag: t.number, color: "#005cc5" },
  { tag: t.integer, color: "#005cc5" },
  { tag: t.float, color: "#005cc5" },
  { tag: t.string, color: "#032f62" },
  { tag: t.docString, color: "#032f62" },
  { tag: t.character, color: "#032f62" },
  { tag: t.escape, color: "#005cc5" },
  { tag: t.regexp, color: "#032f62" },
  { tag: t.variableName, color: "#24292e" },
  { tag: t.propertyName, color: "#6f42c1" },
  { tag: t.function(t.variableName), color: "#6f42c1" },
  { tag: t.function(t.propertyName), color: "#6f42c1" },
  { tag: t.labelName, color: "#6f42c1" },
  { tag: t.namespace, color: "#005cc5" },
  { tag: t.typeName, color: "#22863a" },
  { tag: t.className, color: "#22863a" },
  { tag: t.macroName, color: "#005cc5" },
  { tag: t.operator, color: "#d73a49" },
  { tag: t.derefOperator, color: "#d73a49" },
  { tag: t.arithmeticOperator, color: "#d73a49" },
  { tag: t.logicOperator, color: "#d73a49" },
  { tag: t.compareOperator, color: "#d73a49" },
  { tag: t.updateOperator, color: "#d73a49" },
  { tag: t.definitionOperator, color: "#d73a49" },
  { tag: t.punctuation, color: "#24292e" },
  { tag: t.separator, color: "#24292e" },
  { tag: t.bracket, color: "#24292e" },
  { tag: t.invalid, color: "#ffffff", backgroundColor: "#d73a49" },
  { tag: t.meta, color: "#6a737d" },
]);

export function defineSyntaxHighlighting(theme: Theme): Extension {
  const style = theme.syntax ?? (theme.variant === "dark" ? darkSyntaxStyle : lightSyntaxStyle);
  return syntaxHighlighting(style);
}
